### ISSUE TITLE
Productos

### ISSUE THREAD

**Issue by enelramon** [Mariopolonia0/PreoyectoFinal_Aplicada1_Eladio_Mario#6]
Existencia se modifica en esta ventana.(al campo existencia no se le deberá modificar directamente o entra por compras o sale por ventas o cualquier opción por el estilo pero no una persona modificando este campo manualmente)

 Revisar el cálculo del itbis al quitarlo y volverlo a poner no me parece que esté bien.

**Comment by Mariopolonia0** [comment]
listo

**Comment by Mariopolonia0** [comment]
listo esta como usted quiere
